---
title: "dataR_01_first_Rmarkdown"
author: "Peter Hahn"
date: "2025-01-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(palmerpenguins)
library(ggthemes)
```

```{r}
penguins
glimpse(penguins)
```
```{r}
ggplot(data = penguins)
```

```{r}
ggplot(
        data = penguins,
        mapping = aes(x = flipper_length_mm, y = body_mass_g)
)
```


```{r}
ggplot(
        data = penguins,
        mapping = aes(x = flipper_length_mm, y = body_mass_g)
) +
        geom_point()
```


```{r}

ggplot(
        data = penguins,
        mapping = aes(x = flipper_length_mm, y = body_mass_g, color = species)
) +
        geom_point()
```

```{r}
ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g, color = species)) +
  geom_point() +
        geom_smooth(method = "lm")
```
```{r}
ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g)) +
  geom_point(mapping = aes(color = species)) +
        geom_smooth(method = "lm")
```
